#!/bin/bash
# this script updates obs
cd ~/opt/obs-studio
git pull
git pull --recurse-submodules
read -n1 -p 'Rebuild OBS? (y|N) ' answer
case $answer in
y|Y)
	cd build
	cmake -DUNIX_STRUCTURE=0 -DCMAKE_INSTALL_PREFIX="${HOME}/obs-studio-portable" -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_3770_linux64" ..
	make -j4 && make install ;;
*) 
	;;
esac
echo
echo 'Returning to'
cd -
