#!/bin/bash

# set cable with fixed ip
#sudo ip link set cable0 up && sudo ip address flush dev cable0 && sudo ip address add 192.168.1.41/24 broadcast + dev cable0 && sudo ip route add default via 192.168.1.1 dev cable0
# set virtualcameras
#sudo modprobe -r v4l2loopback && sudo modprobe v4l2loopback devices=2 video_nr=10,20 card_label=TimerCam,StreamCam
# open zoom
#zoom </dev/null &>/dev/null &
#disown -h %1
# open obs
cd ~/obs-studio-portable/bin/64bit
./obs </dev/null &>/dev/null &
disown -h %1
cd
